---
npm:
  environment:
    - name: CCACHE_TEMPDIR
      value: /tmp/.ccache-temp
    - name: CCACHE_COMPRESS
      value: 1
    - name: CC
      value: clang
    - name: CXX
      value: clang++
  platforms:
    - name: linux
      os: ubuntu
      architecture: x86_64
      node_versions:
        - "12"
        - "10"
    - name: linux
      os: ubuntu
      architecture: x86
      node_versions:
        - "12"
        - "10"
    - name: darwin
      os: macos
      architecture: x86_64
      node_versions:
        - "12"
        - "10"
    - name: windows
      os: windows
      architecture: x86_64
      node_versions:
        - "12"
        - "10"
    - name: windows
      os: windows
      architecture: x86
      node_versions:
        - "12"
        - "10"
