language: node_js
node_js:
  - 10
  - 8
  - 6
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install --user -r requirements.txt;
    else
      pip2 install -r requirements.txt;
    fi
script:
  - npm test
compiler: clang-4.0
env:
  global:
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CC="clang"
    - CXX="clang++"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: script
  script: ./ci/prebuild-publish.sh
  on:
    node: 10
    tags: true
    branch: master
